_format_version: "3.0"
_konnect:
  control_plane_name: hello-default
plugins:
- config:
    day: null
    error_code: 429
    error_message: API rate limit exceeded
    fault_tolerant: true
    header_name: null
    hide_client_headers: false
    hour: null
    limit_by: consumer
    minute: 10
    month: null
    path: null
    policy: local
    redis:
      database: 0
      host: null
      password: null
      port: 6379
      server_name: null
      ssl: false
      ssl_verify: false
      timeout: 2000
      username: null
    redis_database: 0
    redis_host: null
    redis_password: null
    redis_port: 6379
    redis_server_name: null
    redis_ssl: false
    redis_ssl_verify: false
    redis_timeout: 2000
    redis_username: null
    second: null
    sync_rate: -1
    year: null
  enabled: true
  name: rate-limiting
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: 52.206.9.54
  name: crapi-rest-service
  path: /
  port: 8888
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: crapi-route
    path_handling: v0
    paths:
    - /
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: 52.206.9.54
  name: hello-graphql-service
  path: /graphql
  port: 8181
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    methods:
    - POST
    name: hello-graphql-route
    path_handling: v0
    paths:
    - /graphql
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: 52.206.9.54
  name: hello-web-service
  path: /
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: hello-app-route
    path_handling: v0
    paths:
    - /hello
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
